#!/usr/bin/env python3
"""`.cursor/hooks/complexity-guard.py` — Hook that blocks Python edits which
violate complexity budgets.

Three modes:

- `--pre` (Cursor `preToolUse` on Write/StrReplace): build the prospective
  file from tool arguments, measure it, and deny with
  `permission: deny` before anything hits disk. Fails closed.
- No flag (Cursor `afterFileEdit` / `postToolUse`, e.g. TabWrite): measure
  the file already on disk and inject `additional_context`. Fails open.
- `--check` (pre-commit merge gate): measure every tracked `.py` in the
  index. Fails closed. A silent pass here hides real regressions.

Budgets (per function):
    cyclomatic complexity <= 10   (+1 per branch point: if/elif, loops,
                                   except, assert, ternary, and/or,
                                   comprehension clauses, match cases)
    function length       <= 40   (code lines from `def` to last line;
                                   decorators, the docstring, blank lines
                                   and comment-only lines are excluded, so
                                   a long explanation of an invariant does
                                   not read as complexity)
    nesting depth         <= 3    (compound statements; an elif chain does
                                   not add depth; nested defs are measured
                                   as their own functions)
    parameters            <= 6    (a leading self/cls is excluded;
                                   *args and **kwargs count as one each)

Skipped entirely: test files (test_*.py, *_test.py, conftest.py, or
anything under a tests/ directory), anything under an alembic/ directory
(autogenerated migration bodies routinely exceed the budgets), and
anything under scripts/dev/ (undeployed, untested developer tools).

The hook anchors to HEAD. A breach blocks only when it is new or worse
than the committed file. Debt a teammate already committed therefore
stops blocking later edits to that file; `--check` is what keeps it from
merging. A renamed file has no `HEAD:<new path>`, so every breach in it
blocks.

Post-edit mode fails open (exit 0) on garbage stdin, missing file, or a
file the host interpreter cannot parse — a broken advisory hook must not
freeze the session. `--pre` and `--check` do not fail open.

Ruff lint/format stay on `afterFileEdit` and run only after a write is
allowed. Format does not change cyclomatic complexity, parameters, or
nesting; function length ignores blanks and comments.

Every hook run appends one JSON object to
`.test-reports/complexity-guard.jsonl`. Every record carries `ts`, `result`
and `detail`; a record from a completed run also carries `session_id`,
`tool_name`, `file` and `python`. The short shape is what an early
fail-open writes, so a reader must not filter on `file` — that drops
exactly the records showing the guard did not run. `result` is one of
`skip`, `exempt`, `pass`, `block`, `fail-open`, or `fail-closed`.

Scope differs between the paths. Edit hooks check whatever file the tool
named, tracked or not. `--check` measures git's index (`git ls-files -c`),
so a local scratch file never turns the gate red.
"""

from __future__ import annotations

import argparse
import ast
import itertools
import json
import os
import platform
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

# One file record maps a repo-relative path to {qualified name: {metric: value}}.
Functions = dict[str, dict[str, dict[str, int]]]

# The gate mode refuses an older interpreter. Matches `target-version` in
# pyproject.toml: the repo uses syntax that earlier pythons cannot parse.
_MIN_GATE_PYTHON = (3, 12)

MAX_COMPLEXITY = 10
MAX_FUNCTION_LINES = 40
MAX_NESTING_DEPTH = 3
MAX_PARAMETERS = 6

_LIMITS = {
    "cyclomatic complexity": MAX_COMPLEXITY,
    "function length": MAX_FUNCTION_LINES,
    "nesting depth": MAX_NESTING_DEPTH,
    "parameters": MAX_PARAMETERS,
}
_UNITS = {"function length": " code lines"}

# The advice the block report ends with. It names the forbidden repairs as
# well as the legitimate ones: "extract a helper" alone moves a breach from
# one function to two, and the budgets then read as met.
# AGENTS.md § "Repairing an over-budget function" states the same four
# repairs and the same three prohibitions, because the agent reads that
# file before it writes. Nothing checks that the two texts agree — edit
# both together.
_REPORT_FOOTER = (
    "Repair these functions in this order. Stop at the first repair that\n"
    "works.\n"
    "  1. Remove a branch. A condition that cannot be false is dead weight.\n"
    "  2. Replace a nested conditional with an early return.\n"
    "  3. Move a whole responsibility to a new named unit. The caller then\n"
    "     stops doing that work.\n"
    "  4. Extract a helper only when the helper has its own reason to\n"
    "     exist. The caller keeps the work; the helper only names a part\n"
    "     of it.\n"
    "\n"
    "Do not use these repairs. Each one moves the breach. None removes it.\n"
    "  - Do not add a boolean parameter to merge two behaviours into one\n"
    "    function.\n"
    "  - Do not pass a dictionary or an object of state to get below the\n"
    "    parameter budget.\n"
    "  - Do not split a function into two halves that share most of their\n"
    "    local variables.\n"
    "\n"
    "Only breaches that are new or worse than the committed file (HEAD)\n"
    "are listed. Pre-existing debt does not block."
)

_FUNCTION_NODES = (ast.FunctionDef, ast.AsyncFunctionDef)
_SCOPE_NODES = (*_FUNCTION_NODES, ast.ClassDef)
_BRANCH_NODES = (
    ast.If,
    ast.IfExp,
    ast.For,
    ast.AsyncFor,
    ast.While,
    ast.ExceptHandler,
    ast.Assert,
)
# getattr keeps the script running on host pythons older than 3.12.
_MATCH_CASE = getattr(ast, "match_case", None)
_NESTING_NODES = tuple(
    node
    for node in (
        ast.If,
        ast.For,
        ast.AsyncFor,
        ast.While,
        ast.With,
        ast.AsyncWith,
        ast.Try,
        getattr(ast, "TryStar", None),
        getattr(ast, "Match", None),
    )
    if node is not None
)


def _tool_input(payload: dict) -> dict:
    """Native Claude/Cursor tool_input, plus Cursor afterFileEdit file_path."""
    raw = payload.get("tool_input")
    tool_input = dict(raw) if isinstance(raw, dict) else {}
    if payload.get("file_path") and not (
        tool_input.get("file_path") or tool_input.get("path")
    ):
        tool_input["file_path"] = payload["file_path"]
    return tool_input


def _target_file(tool_input: dict) -> Path | None:
    """Resolve the edited file from Claude, Cursor, or serena tool input.

    Cursor Write/StrReplace send `path`. Cursor afterFileEdit sends
    `file_path` on the payload (folded in by `_tool_input`). serena's
    replace_in_files carries no single path — that edit is not checked.
    """
    raw = (
        tool_input.get("file_path")
        or tool_input.get("path")
        or tool_input.get("relative_path")
        or ""
    )
    if not raw:
        return None
    path = Path(raw)
    if not path.is_absolute():
        root = os.environ.get("CLAUDE_PROJECT_DIR", "")
        path = Path(root) / path if root else path.resolve()
    return path


def _in_dev_scripts(parts: tuple[str, ...]) -> bool:
    """True for a path under `scripts/dev/`.

    Those files are developer tools. They are not deployed and they have no
    tests, so a refactor there carries risk without a safety net — the same
    reason `tests/` and `alembic/` are exempt.
    """
    return any(
        left == "scripts" and right == "dev"
        for left, right in itertools.pairwise(parts)
    )


def _is_exempt_file(path: Path) -> bool:
    parts = path.parts
    return (
        "alembic" in parts
        or "tests" in parts
        or _in_dev_scripts(parts)
        or path.name.startswith("test_")
        or path.name.endswith("_test.py")
        or path.name == "conftest.py"
    )


def _collect_functions(
    tree: ast.AST,
) -> list[tuple[str, ast.FunctionDef | ast.AsyncFunctionDef]]:
    """All function defs in the tree, paired with their qualified name."""
    found: list[tuple[str, ast.FunctionDef | ast.AsyncFunctionDef]] = []

    def visit(node: ast.AST, prefix: str) -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, _FUNCTION_NODES):
                found.append((prefix + child.name, child))
                visit(child, prefix + child.name + ".")
            elif isinstance(child, ast.ClassDef):
                visit(child, prefix + child.name + ".")
            else:
                visit(child, prefix)

    visit(tree, "")
    return found


def _walk_scope(func: ast.FunctionDef | ast.AsyncFunctionDef):
    """Walk a function's body, not descending into nested scopes.

    Seeding from the body (not iter_child_nodes) keeps decorator and
    argument-default expressions out of the complexity count, matching
    the length metric, which excludes decorators too. Lambda bodies stay
    in: their branches live inline in the enclosing function's code.
    """
    stack: list[ast.AST] = list(func.body)
    while stack:
        node = stack.pop()
        if isinstance(node, _SCOPE_NODES):
            continue
        yield node
        stack.extend(ast.iter_child_nodes(node))


def _branch_increment(node: ast.AST) -> int:
    if isinstance(node, _BRANCH_NODES):
        return 1
    if isinstance(node, ast.BoolOp):
        return len(node.values) - 1
    if isinstance(node, ast.comprehension):
        return 1 + len(node.ifs)
    if _MATCH_CASE is not None and isinstance(node, _MATCH_CASE):
        return 0 if _is_wildcard_case(node) else 1
    return 0


def _is_wildcard_case(case: ast.match_case) -> bool:
    """A bare `case _:` is the match analogue of `else:` — no branch added.

    Only called when the host python has match statements, so ast.MatchAs
    is guaranteed to exist here.
    """
    return (
        case.guard is None
        and isinstance(case.pattern, ast.MatchAs)
        and case.pattern.pattern is None
    )


def _cyclomatic_complexity(func: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    return 1 + sum(_branch_increment(node) for node in _walk_scope(func))


def _is_elif(parent: ast.AST, child: ast.AST) -> bool:
    return (
        isinstance(parent, ast.If)
        and isinstance(child, ast.If)
        and parent.orelse == [child]
        and parent.col_offset == child.col_offset
    )


def _max_nesting(node: ast.AST, enclosing: int) -> int:
    """Deepest count of stacked compound statements under `node`."""
    deepest = enclosing
    for child in ast.iter_child_nodes(node):
        if isinstance(child, _SCOPE_NODES):
            continue
        if isinstance(child, _NESTING_NODES):
            inner = enclosing if _is_elif(node, child) else enclosing + 1
            deepest = max(deepest, inner, _max_nesting(child, inner))
        else:
            deepest = max(deepest, _max_nesting(child, enclosing))
    return deepest


def _parameter_count(func: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    args = func.args
    positional = list(args.posonlyargs) + list(args.args)
    count = len(positional) + len(args.kwonlyargs)
    count += 1 if args.vararg else 0
    count += 1 if args.kwarg else 0
    if positional and positional[0].arg in ("self", "cls"):
        count -= 1
    return count


def _end_line(node: ast.stmt) -> int:
    """The last source line of `node`.

    `ast.parse` sets `end_lineno` on every statement, so the fallback is
    unreachable for a node the guard measures. The annotation is `int | None`
    because a hand-built node may omit it. Fall back to the first line: a
    one-line span under-reports, which fails open, and this guard fails open
    everywhere else too.
    """
    return node.lineno if node.end_lineno is None else node.end_lineno


def _docstring_lines(func: ast.FunctionDef | ast.AsyncFunctionDef) -> set[int]:
    """Every line a docstring occupies inside `func`, its own included.

    A nested helper's docstring is prose in the enclosing function's span
    too, so it must not count as the enclosing function's code either.
    """
    excluded: set[int] = set()
    for node in ast.walk(func):
        if not isinstance(node, _SCOPE_NODES):
            continue
        first = node.body[0] if node.body else None
        if (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
        ):
            excluded.update(range(first.lineno, _end_line(first) + 1))
    return excluded


def _code_line_count(
    func: ast.FunctionDef | ast.AsyncFunctionDef, lines: list[str]
) -> int:
    """Lines of real code from `def` to the last line of the body.

    Docstrings, blank lines and comment-only lines do not count: a long
    explanation of an invariant is documentation, not complexity, and a
    budget that counts it rewards deleting the explanation. Decorators are
    already outside the span because `lineno` points at the `def`. A nested
    def's code still counts toward the enclosing function, as it did when
    this metric was a raw line span.
    """
    docstrings = _docstring_lines(func)
    count = 0
    for number in range(func.lineno, _end_line(func) + 1):
        stripped = lines[number - 1].strip()
        if number not in docstrings and stripped and not stripped.startswith("#"):
            count += 1
    return count


def _metrics(
    func: ast.FunctionDef | ast.AsyncFunctionDef, lines: list[str]
) -> dict[str, int]:
    """Every budgeted metric of one function, as {metric name: measured value}."""
    return {
        "cyclomatic complexity": _cyclomatic_complexity(func),
        "function length": _code_line_count(func, lines),
        "nesting depth": _max_nesting(func, 0),
        "parameters": _parameter_count(func),
    }


def _over_budget(
    func: ast.FunctionDef | ast.AsyncFunctionDef, lines: list[str]
) -> dict[str, int]:
    """Every budget this function exceeds, as {metric name: measured value}."""
    measured = _metrics(func, lines)
    return {name: value for name, value in measured.items() if value > _LIMITS[name]}


def _blocking(over: dict[str, int], recorded: dict[str, int]) -> list[str]:
    """Messages for the breaches that are new or worse than HEAD.

    A breach HEAD already records at the same value or higher is not
    reported: the debt was there before this edit, and making the whole file
    a precondition for touching one line of it is what the HEAD anchor
    removes.
    """
    messages = []
    for name, value in over.items():
        was = recorded.get(name)
        if was is not None and value <= was:
            continue
        suffix = "" if was is None else f", was {was}"
        unit = _UNITS.get(name, "")
        messages.append(f"{name} {value}{unit} (max {_LIMITS[name]}{suffix})")
    return messages


def _report_block(
    name: str,
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    lines: list[str],
    recorded: dict[str, int],
) -> str:
    violations = _blocking(_over_budget(func, lines), recorded)
    if not violations:
        return ""
    block = [f"  {name} (line {func.lineno}):"]
    block += [f"    {violation}" for violation in violations]
    return "\n".join(block)


def _repo_root() -> Path:
    """Resolved, because `_relative_key` compares it against a resolved path.

    An unresolved CLAUDE_PROJECT_DIR that traverses a symlink (on macOS
    /var and /tmp both do) makes `relative_to` raise, and every file key
    silently misses.
    """
    root = os.environ.get("CLAUDE_PROJECT_DIR", "")
    return Path(root).resolve() if root else Path(__file__).resolve().parents[2]


# One JSON object per hook run, appended. Not `.log`: `make ci` deletes
# .test-reports/*.log at start, and the point of this file is that a run
# leaves a record even when the agent never reports one.
LOG_PATH = _repo_root() / ".test-reports" / "complexity-guard.jsonl"


def _now() -> str:
    """The current time as a UTC ISO 8601 string."""
    return datetime.now(UTC).isoformat()


def _log_run(record: dict[str, object]) -> None:
    """Append one record to the run log.

    Never raises and never prints. A logger that could block an edit would
    be a worse defect than the missing observability it fixes.
    """
    try:
        LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with LOG_PATH.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(record) + "\n")
    except Exception:  # noqa: BLE001
        return


def _agent_context(message: str) -> str:
    """JSON the agent sees: Cursor additional_context plus Claude PostToolUse."""
    return json.dumps(
        {
            "additional_context": message,
            "hookSpecificOutput": {
                "hookEventName": "PostToolUse",
                "additionalContext": message,
            },
        }
    )


def _fail_open_context(reason: str) -> str:
    """Tell the agent the guard failed open.

    Without it a fail-open is indistinguishable from a clean pass, which is
    how a broken guard stays broken for a whole session.
    """
    return _agent_context(
        f"complexity-guard failed open: {reason}. "
        "See .test-reports/complexity-guard.jsonl"
    )


def _relative_key(path: Path) -> str:
    """The repo-relative posix path reports and HEAD lookup use for `path`."""
    try:
        return path.resolve().relative_to(_repo_root()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _entries_from_source(
    source: bytes, filename: str, strict: bool = False
) -> dict[str, dict[str, int]]:
    """Every over-budget function in `source`, keyed by qualified name.

    Takes bytes rather than a path so the same measurement serves the
    working tree and the version `git show` hands back for HEAD.

    `strict` is what separates the two callers. The hook treats an
    unparseable file as "nothing to say", which is right for one edit. A
    gate must not: a file the host interpreter cannot parse would measure
    as zero debt, and every breach it holds would read as a clean tree.
    """
    try:
        tree = ast.parse(source, filename=filename)
    except (SyntaxError, ValueError):
        if strict:
            raise
        return {}
    lines = _source_lines(source)
    entries = {}
    for name, func in _collect_functions(tree):
        over = _over_budget(func, lines)
        if over:
            entries[name] = over
    return entries


def _head_source(key: str) -> bytes | None:
    """The committed bytes of `key`, or None when HEAD does not hold it.

    None covers every reason: a new or renamed file, a detached or empty
    HEAD, and a host with no `git` at all (OSError covers the missing
    binary). The caller then treats the file as having no recorded debt,
    so every current breach blocks.
    """
    try:
        result = subprocess.run(
            ["git", "show", f"HEAD:{key}"],
            cwd=_repo_root(),
            capture_output=True,
            check=False,
        )
    except OSError:
        return None
    return result.stdout if result.returncode == 0 else None


def _head_entries(path: Path) -> dict[str, dict[str, int]]:
    """The over-budget functions of the committed version of `path`."""
    key = _relative_key(path)
    source = _head_source(key)
    return {} if source is None else _entries_from_source(source, key)


def _source_lines(source: bytes) -> list[str]:
    """Physical lines, indexable by `ast` line number minus one.

    split("\\n"), not splitlines(): splitlines also breaks on form feed and
    U+2028, which ast does not count as line ends, and one such character
    would shift every later line number by one. `ast.parse` honours a PEP 263
    coding declaration and this decode does not, but it only feeds
    blank/comment detection, and every encoding python accepts here splits
    lines the same way. "replace" keeps a mismatch from raising.
    """
    return source.decode("utf-8", "replace").split("\n")


def _analyze_source(path: Path, source: bytes) -> str:
    """Return a violation report for `source`, or "" if nothing new is wrong."""
    try:
        tree = ast.parse(source, filename=str(path))
    except (SyntaxError, ValueError):
        return ""
    lines = _source_lines(source)
    recorded = _head_entries(path)
    blocks = [
        block
        for name, func in _collect_functions(tree)
        if (block := _report_block(name, func, lines, recorded.get(name, {})))
    ]
    if not blocks:
        return ""
    return "\n\n".join(
        [f"Complexity budget violations in {path}:", *blocks, _REPORT_FOOTER]
    )


def _analyze(path: Path) -> str:
    """Return a violation report for on-disk `path`, or "" if nothing new is wrong."""
    try:
        source = path.read_bytes()
    except OSError:
        return ""
    return _analyze_source(path, source)


def _write_prospective(tool_input: dict) -> bytes | None:
    """Full file bytes from a Write tool_input, or None when contents are absent."""
    raw = tool_input.get("contents")
    if raw is None:
        raw = tool_input.get("content")
    if not isinstance(raw, str):
        return None
    return raw.encode("utf-8")


def _apply_str_replace(current: str, tool_input: dict) -> str | None:
    """Apply one StrReplace to `current`, or None when the edit cannot apply."""
    old = tool_input.get("old_string")
    new = tool_input.get("new_string")
    if not isinstance(old, str) or not isinstance(new, str):
        return None
    if old not in current:
        return None
    if tool_input.get("replace_all"):
        return current.replace(old, new)
    return current.replace(old, new, 1)


def _str_replace_prospective(path: Path, tool_input: dict) -> bytes | None:
    """Prospective file bytes after StrReplace, or None when it cannot be built."""
    try:
        current = path.read_text(encoding="utf-8")
    except OSError:
        return None
    updated = _apply_str_replace(current, tool_input)
    return None if updated is None else updated.encode("utf-8")


def _is_str_replace(tool_name: str, tool_input: dict) -> bool:
    return tool_name == "StrReplace" or "old_string" in tool_input


def _prospective_bytes(path: Path, payload: dict, tool_input: dict) -> bytes | None:
    """Bytes the tool would write, built from arguments without touching disk writes."""
    tool_name = str(payload.get("tool_name") or "")
    if _is_str_replace(tool_name, tool_input):
        return _str_replace_prospective(path, tool_input)
    return _write_prospective(tool_input)


def _emit_permission(permission: str, *, agent_message: str | None = None) -> int:
    """Print a Cursor preToolUse permission verdict and return the exit code."""
    body: dict[str, str] = {"permission": permission}
    if agent_message is not None:
        body["agent_message"] = agent_message
        body["user_message"] = (
            "Complexity budget violation — edit blocked before write."
        )
        print(agent_message, file=sys.stderr)
    print(json.dumps(body))
    return 2 if permission == "deny" else 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse mode flags. Bare hook mode (post-edit) passes no arguments.

    A usage error exits 1, never argparse's default 2: 2 is the deny / block
    code, so a hook registered with a stray argument would deny every Python
    edit in the session and show an argparse usage string as the report.
    """
    parser = argparse.ArgumentParser(prog="complexity-guard.py")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--pre", action="store_true")
    parser.add_argument("--report", metavar="FILE")
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        # argparse exits 2 on a usage error and 0 on --help. Keep --help at
        # 0; anything else becomes 1, never 2.
        raise SystemExit(0 if exc.code == 0 else 1) from exc
    modes = (args.check, args.pre, args.report is not None)
    if sum(modes) != 1:
        print("error: pass one of --check, --pre or --report", file=sys.stderr)
        raise SystemExit(1)
    return args


def tracked_python_files(root: Path) -> list[str]:
    """Every tracked `.py` path, as git's index records it.

    The index, not the working tree: a local scratch file must not turn the
    gate red. A new file therefore has to be staged before `--check` sees
    it. Errors propagate — a gate that silently measured nothing would hide
    every regression at once.

    `-z` with `core.quotePath=off` because git C-quotes a non-ASCII path by
    default (`"src/app/caf\\303\\251.py"`). That name resolves to no file on
    disk, and the file's whole debt would silently drop out.
    """
    listing = subprocess.run(
        ["git", "-c", "core.quotePath=off", "ls-files", "-z", "-c", "--", "*.py"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    return [name for name in listing.stdout.split("\0") if name]


def measure_tree(root: Path) -> Functions:
    """Today's breaches across the index.

    Exemption is decided on the repo-relative path, never the absolute one:
    `_is_exempt_file` looks for a `tests` or `alembic` path component, and a
    checkout that happens to live under a directory of that name would
    otherwise exempt the entire repository and report zero debt.

    A path the index still lists but the working tree no longer holds is
    skipped, so an unstaged delete does not crash the gate. A file that
    exists but cannot be read or parsed is fatal: measuring it as zero debt
    is how a gate reports a clean tree instead of a failure.
    """
    functions: Functions = {}
    for name in tracked_python_files(root):
        path = root / name
        if _is_exempt_file(Path(name)):
            continue
        if not path.is_file():
            continue
        entries = _entries_from_source(path.read_bytes(), name, strict=True)
        if entries:
            functions[name] = entries
    return functions


def _debt_lines(functions: Functions) -> list[str]:
    """Every over-budget metric, one reviewable line each."""
    return [
        f"{file_key}::{func_name}  {metric} {value}{_UNITS.get(metric, '')} "
        f"(max {_LIMITS[metric]})"
        for file_key, entries in sorted(functions.items())
        for func_name, metrics in sorted(entries.items())
        for metric, value in sorted(metrics.items())
    ]


def _report_lines(path: Path, source: bytes) -> list[str]:
    """One line per function: each measured metric against its budget."""
    tree = ast.parse(source, filename=str(path))
    lines = _source_lines(source)
    return [
        f"{name} (line {func.lineno}): "
        + ", ".join(
            f"{metric} {value}/{_LIMITS[metric]}"
            for metric, value in _metrics(func, lines).items()
        )
        for name, func in _collect_functions(tree)
    ]


def report(path: Path) -> int:
    """Print the budget headroom of every function in one file.

    A reader that needs these numbers otherwise reads this whole file to
    estimate them, and then restates the budgets somewhere they can drift.
    """
    if _is_exempt_file(path):
        print(f"complexity-report: {path} is exempt from the budgets")
        return 0
    try:
        lines = _report_lines(path, path.read_bytes())
    except (OSError, SyntaxError, ValueError) as exc:
        print(f"complexity-report: cannot measure {path}: {exc}", file=sys.stderr)
        return 1
    print("\n".join(lines) or f"complexity-report: {path} declares no function")
    return 0


def _require_gate_interpreter() -> None:
    """Refuse a gate run on an interpreter older than the project target.

    Two interpreters only measure the same numbers while they parse the
    same syntax. This repo targets python 3.12. An older host silently
    drops every function it cannot parse. The gate then reports a clean
    tree. Failing loud here is the difference between a missed breach and
    a silent pass.
    """
    if sys.version_info < _MIN_GATE_PYTHON:
        wanted = ".".join(str(part) for part in _MIN_GATE_PYTHON)
        print(
            f"error: the gate modes need python >= {wanted}, "
            f"got {platform.python_version()} at {sys.executable}",
            file=sys.stderr,
        )
        raise SystemExit(1)


def check() -> int:
    """Fail when any tracked function is over budget.

    The edit hooks only see the file this tool named. An edit made outside a
    hooked session, or debt already on HEAD, still has to reach zero
    before it can merge.
    """
    measured = measure_tree(_repo_root())
    violations = _debt_lines(measured)
    if not violations:
        print("complexity-check: no over-budget functions")
        return 0
    for line in violations:
        print(line)
    print(
        "complexity-check: the tree has over-budget functions. "
        "Bring each function within budget."
    )
    return 1


def _base_record(payload: dict, path: Path | None) -> dict[str, object]:
    """The fields every hook record carries, whatever the outcome."""
    return {
        "ts": _now(),
        "session_id": payload.get("session_id"),
        "tool_name": payload.get("tool_name"),
        "file": _relative_key(path) if path is not None else None,
        "python": platform.python_version(),
    }


def _run_hook(payload: dict) -> tuple[int, str, str | None]:
    """The post-edit hook decision for one file already on disk.

    Exemption is decided on the repo-relative path, never the absolute one,
    for the reason `measure_tree` documents: a checkout under a directory
    named `tests` or `alembic` would otherwise exempt every file in it and
    the hook would silently pass for a whole session.
    """
    path = _target_file(_tool_input(payload))
    if path is None or path.suffix.lower() != ".py":
        return 0, "skip", None
    if _is_exempt_file(Path(_relative_key(path))):
        return 0, "exempt", None
    report = _analyze(path)
    if report:
        return 2, "block", report
    return 0, "pass", None


def _run_pre(payload: dict) -> tuple[int, str, str | None, Path | None]:
    """The preToolUse decision for prospective Write/StrReplace contents."""
    tool_input = _tool_input(payload)
    path = _target_file(tool_input)
    if path is None or path.suffix.lower() != ".py":
        return 0, "skip", None, path
    if _is_exempt_file(Path(_relative_key(path))):
        return 0, "exempt", None, path
    source = _prospective_bytes(path, payload, tool_input)
    if source is None:
        detail = (
            f"complexity-guard --pre: could not build prospective source for {path}"
        )
        return 2, "block", detail, path
    report = _analyze_source(path, source)
    if report:
        return 2, "block", report, path
    return 0, "pass", None, path


def main() -> int:
    """Post-edit advisory hook. Fails open on broken input or unexpected errors."""
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, UnicodeDecodeError):
        payload = None
    record: dict[str, object] = {"ts": _now(), "python": platform.python_version()}
    if not isinstance(payload, dict):
        record.update(result="fail-open", detail="unreadable stdin")
        _log_run(record)
        return 0
    try:
        record = _base_record(payload, _target_file(_tool_input(payload)))
        code, result, detail = _run_hook(payload)
    except Exception as exc:  # noqa: BLE001
        record.update(result="fail-open", detail=repr(exc))
        _log_run(record)
        print(_fail_open_context(repr(exc)))
        return 0
    record.update(result=result, detail=detail)
    _log_run(record)
    if result == "block" and detail:
        print(detail, file=sys.stderr)
        print(_agent_context(detail))
    return code


def pre_main() -> int:
    """preToolUse gate. Denies before disk write; fails closed on errors."""
    record: dict[str, object] = {"ts": _now(), "python": platform.python_version()}
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, UnicodeDecodeError):
        record.update(result="fail-closed", detail="unreadable stdin")
        _log_run(record)
        return _emit_permission(
            "deny",
            agent_message="complexity-guard --pre: unreadable stdin",
        )
    if not isinstance(payload, dict):
        record.update(result="fail-closed", detail="non-object stdin")
        _log_run(record)
        return _emit_permission(
            "deny",
            agent_message="complexity-guard --pre: non-object stdin",
        )
    try:
        _code, result, detail, path = _run_pre(payload)
        record = _base_record(payload, path)
        record.update(result=result, detail=detail)
        _log_run(record)
        if result == "block" and detail:
            return _emit_permission("deny", agent_message=detail)
        return _emit_permission("allow")
    except Exception as exc:  # noqa: BLE001
        record.update(result="fail-closed", detail=repr(exc))
        _log_run(record)
        return _emit_permission(
            "deny",
            agent_message=f"complexity-guard --pre failed: {exc!r}",
        )


if __name__ == "__main__":
    # Gate modes are deliberately outside the post-edit fail-open wrapper: a
    # check that silently did nothing would hide every regression at once.
    if sys.argv[1:]:
        mode = parse_args(sys.argv[1:])
        if mode.pre:
            sys.exit(pre_main())
        _require_gate_interpreter()
        sys.exit(report(Path(mode.report)) if mode.report else check())
    try:
        sys.exit(main())
    except Exception as _exc:  # noqa: BLE001
        _log_run({"ts": _now(), "result": "fail-open", "detail": repr(_exc)})
        sys.exit(0)
